# Docs for the Azure Web Apps Deploy action: https://github.com/Azure/webapps-deploy
# More GitHub Actions for Azure: https://github.com/Azure/actions

name: Build and deploy container app to Azure Web App - pruebafinal1cg

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: 'ubuntu-latest'

    steps:
    - uses: actions/checkout@v2

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1

    - name: Log in to registry
      uses: docker/login-action@v1
      with:
        registry: https://index.docker.io/v1/
        username: ${{ secrets.AzureAppService_ContainerUsername_99d4ae83b99a4d969796f7221d477957 }}
        password: ${{ secrets.AzureAppService_ContainerPassword_67e03e51604948b48d0786d7ea04f7e4 }}

    - name: Build and push container image to registry
      uses: docker/build-push-action@v2
      with:
        push: true
        tags: index.docker.io/${{ secrets.AzureAppService_ContainerUsername_99d4ae83b99a4d969796f7221d477957 }}/edwin17/angular:${{ github.sha }}
        file: ./Dockerfile

  deploy:
    runs-on: ubuntu-latest
    needs: build
    environment:
      name: 'production'
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}

    steps:
    - name: Deploy to Azure Web App
      id: deploy-to-webapp
      uses: azure/webapps-deploy@v2
      with:
        app-name: 'pruebafinal1cg'
        slot-name: 'production'
        publish-profile: ${{ secrets.AzureAppService_PublishProfile_ba4320924e644b18b067fa38ab3d631b }}
        images: 'index.docker.io/${{ secrets.AzureAppService_ContainerUsername_99d4ae83b99a4d969796f7221d477957 }}/edwin17/angular:${{ github.sha }}'